import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const linkClasses =
    "text-white font-bold uppercase tracking-widest text-[20px]";
  return (
    <html lang="en">
      <body>
        <header className="bg-indigo-500 p-4 text-center flex justify-center gap-10">
          <Link className={linkClasses} href="/products">
            Products
          </Link>
          <Link className={linkClasses} href="/blog">
            Blog
          </Link>
          <Link className={linkClasses} href="/mydocs">
            Docs
          </Link>
          <Link className={linkClasses} href="/login">
            Login
          </Link>
        </header>
        <main className="mx-4 p-2">{children}</main>
        <footer className="bg-gray-200 p-4 absolute bottom-0 w-full text-center">
          Footer
        </footer>
      </body>
    </html>
  );
}
