import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-amber-500 p-4 text-center">Header</header>
        <main className="mx-4 p-2">{children}</main>
        <footer className="bg-gray-200 p-4 absolute bottom-0 w-full text-center">
          Footer
        </footer>
      </body>
    </html>
  );
}
