import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Link href="/dashboard">Dashboard (Static)</Link>
          <Link href="/about">About (Dynamic)</Link>
          <Link href="/products">Products (SSG)</Link>
          <Link href="/product-reviews">Review Product (Streaming)</Link>
          <Link href="/client-route">Client Route</Link>
          <Link href="/server-route">Server Route</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
